name: Linux x64 Build

on:
  push:
    paths-ignore:
      - '**.js'
      - '**.dfn'
      - '**.scp'
  pull_request:
    paths-ignore:
      - '**.js'
      - '**.dfn'
      - '**.scp'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: cechckout
        uses: actions/checkout@v3
      - name: Create build directory
        run: |
            cd Build
      - name: CMake build
        run: |
            cmake ../source -DCMAKE_BUILD_TYPE=Release  
            cmake --build . --config Release
