name: Linux x64 Build

on:
  push:
    paths-ignore:
      - '**.js'
      - '**.dfn'
      - '**.scp'
  pull_request:
    paths-ignore:
      - '**.js'
      - '**.dfn'
      - '**.scp'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      - name: Create build directory
        run: mkdir build | cd build
      - name: CMake build
        run: cmake ../source -DCMAKE_BUILD_TYPE=Release  
             cmake --build . --config Release
